"""FMOM static tables: ETF proxies, Man style buckets, AQR-65 mapping.

Data, not logic — hand-editable like zenith/cas/beta_etfs.py. The ETF universe
behind the Man styles lives in the committed data/fmom/etf_catalog.json
(Morningstar strategic-beta exports parsed by scripts/parse_beta_spreadsheets.py).
"""

from __future__ import annotations

# --- Phase 1: one liquid, long-lived US ETF per factor/style -----------------
# Signals run on monthly returns in EXCESS of SPY, so a proxy's beta doesn't
# masquerade as factor momentum. "since" = fund inception (backtest depth).
# "char" links the factor to a Russell-1000 characteristic screen (stock finder).
ETF_PROXIES: list[dict] = [
    {"factor": "Value",             "ticker": "VLUE", "name": "iShares MSCI USA Value Factor",      "since": "2013-04",
     "char": "book_to_market",
     "definition": "Cheap stocks: high fundamentals (book value, earnings, sales) per dollar of price.",
     "recipe": "Rank on book-to-market, earnings/price or sales/price; buy the cheapest ~30%."},
    {"factor": "Momentum",          "ticker": "MTUM", "name": "iShares MSCI USA Momentum Factor",   "since": "2013-04",
     "char": "mom_12_2",
     "definition": "Recent winners: stocks with the strongest returns over the past 6-12 months.",
     "recipe": "Rank on the trailing 12-month return skipping the last month (12-2); buy the top ~30%."},
    {"factor": "Quality",           "ticker": "QUAL", "name": "iShares MSCI USA Quality Factor",    "since": "2013-07",
     "char": "roe",
     "definition": "Profitable, stable, low-leverage businesses (high ROE, stable earnings, low debt).",
     "recipe": "Rank on return-on-equity with low debt/equity and stable earnings growth; buy the top ~30%."},
    {"factor": "Low Volatility",    "ticker": "USMV", "name": "iShares MSCI USA Min Vol Factor",    "since": "2011-10",
     "char": "ivol",
     "definition": "The calmest stocks: lowest realized/idiosyncratic volatility, defensive tilts.",
     "recipe": "Rank on trailing 1-year volatility (or beta); buy the LOWEST ~30%."},
    {"factor": "Size (small)",      "ticker": "IWM",  "name": "iShares Russell 2000",               "since": "2000-05",
     "char": "mktcap",
     "definition": "Small companies: the size premium is long small caps, short mega caps.",
     "recipe": "Rank on market cap; buy the smallest names in your universe."},
    {"factor": "Dividend Yield",    "ticker": "VYM",  "name": "Vanguard High Dividend Yield",       "since": "2006-11",
     "char": "div_yield",
     "definition": "High current income: above-average dividend yield.",
     "recipe": "Rank on trailing dividend yield; buy the top ~30% (watch for distressed yield traps)."},
    {"factor": "Dividend Growth",   "ticker": "SDY",  "name": "SPDR S&P Dividend Aristocrats",      "since": "2005-11",
     "char": "div_yield",
     "definition": "Consistent dividend growers: 20+ consecutive years of rising payouts.",
     "recipe": "Screen for long streaks of consecutive annual dividend increases, then weight by yield."},
    {"factor": "Growth",            "ticker": "IWF",  "name": "iShares Russell 1000 Growth",        "since": "2000-05",
     "char": "rev_growth",
     "definition": "Expensive-but-expanding: high expected/realized sales and earnings growth.",
     "recipe": "Rank on revenue growth and price/book (growth side); buy the fastest growers."},
    {"factor": "Buyback",           "ticker": "PKW",  "name": "Invesco Buyback Achievers",          "since": "2006-12",
     "char": None,
     "definition": "Net share repurchasers: companies that bought back 5%+ of shares in the past year.",
     "recipe": "Screen for net share-count REDUCTION over trailing 12 months (buybacks > issuance)."},
    {"factor": "Shareholder Yield", "ticker": "SYLD", "name": "Cambria Shareholder Yield",          "since": "2013-05",
     "char": "fcf_to_mv",
     "definition": "Total cash returned: dividends + buybacks + debt paydown as a share of market cap.",
     "recipe": "Sum dividends, net buybacks and net debt reduction; divide by market cap; buy the top decile."},
    {"factor": "Multifactor",       "ticker": "LRGF", "name": "iShares US Equity Factor",           "since": "2015-04",
     "char": None,
     "definition": "Blended exposure: value + momentum + quality + size + low vol in one wrapper.",
     "recipe": "Average a stock's ranks across value, momentum, quality and low-vol screens; buy the best composite."},
    {"factor": "High Beta",         "ticker": "SPHB", "name": "Invesco S&P 500 High Beta",          "since": "2011-05",
     "char": "beta",
     "definition": "The most market-sensitive S&P 500 names (highest trailing beta).",
     "recipe": "Rank on 12-month beta vs the S&P 500; buy the top ~100 (this is the AGGRESSIVE side of BAB)."},
    {"factor": "Fundamentals",      "ticker": "FNDX", "name": "Schwab Fundamental US Large",        "since": "2013-08",
     "char": "sp",
     "definition": "Fundamental indexing: weight by sales, cash flow and dividends+buybacks instead of price.",
     "recipe": "Weight holdings by fundamental size (sales/cash flow/payouts) — overweights cheap-vs-cap names."},
    {"factor": "Equal Weight",      "ticker": "RSP",  "name": "Invesco S&P 500 Equal Weight",       "since": "2003-04",
     "char": None,
     "definition": "Anti-concentration: every S&P 500 name at 0.2% — a small-size + value tilt vs cap weight.",
     "recipe": "Hold the index equal-weighted; rebalance quarterly back to equal."},
    {"factor": "Revenue",           "ticker": "RWL",  "name": "Invesco S&P 500 Revenue",            "since": "2008-02",
     "char": "sp",
     "definition": "Revenue weighting: S&P 500 weighted by trailing sales — a sales/price value tilt.",
     "recipe": "Rank on sales-to-price; overweight the highest revenue per dollar of market cap."},
]

BENCHMARK = "SPY"


def etf_proxy_tickers() -> list[str]:
    return [p["ticker"] for p in ETF_PROXIES]


def proxy_of(factor: str) -> str | None:
    for p in ETF_PROXIES:
        if p["factor"] == factor:
            return p["ticker"]
    return None


# --- Phase 2: Man AHL 13 broad styles (composite membership rules) -----------
# Matched against etf_catalog.json strategic-beta group tags; composite = equal-
# weight mean of member-ETF monthly returns minus SPY (market-neutral framing).
# "Principle-based" has no direct Morningstar group — the closest free-data
# equivalent is the committee/rules/earnings/liquidity-screened cluster, and
# the UI says so. A fund tagged with 3+ core style groups is treated as
# Multifactor rather than polluting a single style.
CORE_STYLE_TAGS = {"Momentum", "Quality", "Value", "Volatility", "Growth",
                   "Small Size", "Dividend"}

MAN_STYLES: dict[str, dict] = {
    "Quality":         {"groups": ["Quality"], "pure": True, "char": "roe",
                        "definition": "Profitable, well-run businesses: high ROE/ROA, healthy margins, low leverage.",
                        "recipe": "Rank on return-on-equity (or gross profitability) with a low-debt screen; buy the top ~30%."},
    "Size":            {"groups": ["Market Capitalization", "Small Size"],
                        "pure": True, "exclude": ["Growth", "Value"],
                        "char": "mktcap",
                        "definition": "Smaller-cap and equal-weight exposure — the size premium vs mega-cap concentration.",
                        "recipe": "Rank on market cap; overweight the smaller names (or hold your index equal-weighted)."},
    "Value":           {"groups": ["Value"], "pure": True, "char": "book_to_market",
                        "definition": "Cheap stocks by fundamentals-per-price: book/market, earnings/price, sales/price.",
                        "recipe": "Rank on book-to-market or earnings yield; buy the cheapest ~30%."},
    "Growth":          {"groups": ["Growth"], "pure": True, "char": "rev_growth",
                        "definition": "Fast expanders: high sales/earnings growth, usually at richer multiples.",
                        "recipe": "Rank on revenue growth (and analyst growth estimates); buy the fastest ~30%."},
    "Dividend":        {"groups": ["Dividend"], "pure": True, "char": "div_yield",
                        "definition": "Dividend payers and growers: above-market income with payout discipline.",
                        "recipe": "Rank on dividend yield with a payout-sustainability screen; buy the top ~30%."},
    "Yield":           {"groups": ["Yield"], "pure": True, "char": "fcf_to_mv",
                        "definition": "Cash-generation yield beyond dividends — free-cash-flow 'cash cows'.",
                        "recipe": "Rank on free cash flow / enterprise value (or /market cap); buy the top decile."},
    "Buyback":         {"groups": ["Buyback/Shareholder Yield"], "pure": False,
                        # the Morningstar export only carries two US buyback
                        # funds; SYLD is a well-known shareholder-yield fund
                        "extra": [{"ticker": "SYLD",
                                   "name": "Cambria Shareholder Yield ETF"}],
                        "char": None,
                        "definition": "Net repurchasers: companies shrinking their share count / returning cash.",
                        "recipe": "Screen for net share-count reduction over the trailing year (buybacks > issuance)."},
    "Low Volatility":  {"groups": ["Volatility"], "pure": True,
                        "exclude": ["Momentum"], "char": "ivol",
                        "definition": "The calmest names: minimum-volatility and low-beta portfolios.",
                        "recipe": "Rank on trailing 1-year volatility or beta; buy the LOWEST ~30%."},
    "Multifactor":     {"multifactor": True, "char": None,
                        "definition": "Blends of 3+ styles (value + momentum + quality + low vol) in one fund.",
                        "recipe": "Average each stock's rank across the single-style screens; buy the best composites."},
    "Momentum":        {"groups": ["Momentum"], "pure": True, "char": "mom_12_2",
                        "definition": "Recent winners keep winning: strongest trailing 6-12 month performers.",
                        "recipe": "Rank on the 12-month return skipping the last month; buy the top ~30%."},
    "Proprietary":     {"groups": ["Proprietary"], "pure": True, "char": None,
                        "definition": "In-house rules that don't fit a standard style box (moats, research scores).",
                        "recipe": "No single formula — inspect each member fund's index methodology (e.g. MOAT = wide-moat + cheapest vs fair value)."},
    "Principle-based": {"groups": ["Committee", "Optimization", "Earnings",
                                   "Liquidity"], "pure": False, "char": None,
                        "definition": "Rules/committee-constructed portfolios: equal-weight boards, earnings-weighted, liquidity screens (closest Morningstar match to Man's category).",
                        "recipe": "No single formula — these follow a stated construction principle rather than one characteristic."},
    "Revenue/Fundamentals": {"groups": ["Fundamentals"], "pure": True, "char": "sp",
                        "definition": "Fundamental- and revenue-weighted indexing: weight by sales/cash flow, not price.",
                        "recipe": "Rank on sales-to-price (revenue per dollar of market cap); overweight the top ~30%."},
}

MAN_MAX_MEMBERS = 10          # per style, by AUM — keeps the price pull sane
MAN_MIN_MEMBERS = 3           # a style needs 3+ live members to enter a month

# groups / category substrings that disqualify a fund from any style composite
MAN_EXCLUDE_GROUPS = {"FixedIncome", "Commodity", "Credit", "Duration",
                      "Maturity", "Fixed", "Sector"}
MAN_EXCLUDE_CATEGORY = ("Foreign", "Emerging", "Global", "World", "India",
                        "Europe", "Japan", "China", "Pacific", "International",
                        "Region", "Bond", "Commodit")

# --- Phase 3: AQR-65 mapping table (published sources + replication chars) ---
# One row per factor in Gupta & Kelly's Exhibit A1. live_source:
#   "sort"   -> Ken French univariate-sort long-short (ds/long/short columns)
#   "factor" -> a published French factor series (ds [+ col])
#   "aqr"    -> an AQR monthly workbook (key into factor_data loaders)
#   None     -> no free monthly-updating source (OSAP deep-history/backtest
#               only; still listed so coverage is honest)
# yf_char names a characteristic the Russell-1000 replication layer can compute
# (yfinance info fields or price/volume history); long = which side the paper
# is long ("high"/"low" characteristic).
def _f(abbr, name, family, live=None, ds=None, long=None, short=None, col=None,
       aqr=None, yf=None, side=None, note=None):
    return {"abbr": abbr, "name": name, "family": family, "live_source": live,
            "ds": ds, "long_col": long, "short_col": short, "col": col,
            "aqr_key": aqr, "yf_char": yf, "long_side": side, "note": note}


AQR65: list[dict] = [
    _f("ABNINV",  "Abnormal capital investment",      "investment"),
    _f("ACC",     "Accruals",                         "quality", live="sort",
       ds="Portfolios_Formed_on_AC", long="Lo 20", short="Hi 20"),
    _f("AD2MV",   "Advertising / market value",       "other"),
    _f("ADVERTCHG", "Change in advertising",          "other"),
    _f("AIM",     "Amihud illiquidity",               "trading", yf="amihud", side="high"),
    _f("ASSETG",  "Asset growth",                     "investment", live="sort",
       ds="Portfolios_Formed_on_INV", long="Lo 30", short="Hi 30",
       yf="asset_growth", side="low"),
    _f("ATO",     "Asset turnover",                   "quality"),
    _f("ATOCHG",  "Change in asset turnover",         "quality"),
    _f("BAB",     "Betting against beta",             "risk", live="aqr", aqr="BAB",
       yf="beta", side="low"),
    _f("BM",      "Book-to-market",                   "valuation", live="sort",
       ds="Portfolios_Formed_on_BE-ME", long="Hi 30", short="Lo 30",
       yf="book_to_market", side="high"),
    _f("CAPTO",   "Capital turnover",                 "quality"),
    _f("CASH",    "Cash holdings",                    "quality",
       yf="cash_to_mv", side="high", note="cash/mktcap approximation"),
    _f("CEGTH",   "Capex growth",                     "investment"),
    _f("CP",      "Cash flow-to-price",               "valuation", live="sort",
       ds="Portfolios_Formed_on_CF-P", long="Hi 30", short="Lo 30",
       yf="cfp", side="high"),
    _f("DCAP",    "Debt capacity",                    "other"),
    _f("DELAY",   "Price delay",                      "trading"),
    _f("DP",      "Dividend yield",                   "valuation", live="sort",
       ds="Portfolios_Formed_on_D-P", long="Hi 30", short="Lo 30",
       yf="div_yield", side="high"),
    _f("ECONS",   "Earnings consistency",             "quality"),
    _f("ENTBM",   "Enterprise book-to-market",        "valuation"),
    _f("ENTMULT", "Enterprise multiple",              "valuation",
       yf="ev_ebitda", side="low"),
    _f("EP",      "Earnings-to-price",                "valuation", live="sort",
       ds="Portfolios_Formed_on_E-P", long="Hi 30", short="Lo 30",
       yf="ep", side="high"),
    _f("EPSMOM",  "EPS momentum",                     "momentum"),
    _f("FREECF",  "Free cash flow-to-book",           "valuation",
       yf="fcf_to_mv", side="high", note="FCF/mktcap approximation"),
    _f("FSCORE",  "Piotroski F-score",                "quality"),
    _f("GRPROF",  "Gross profitability",              "quality", live="sort",
       ds="Portfolios_Formed_on_OP", long="Hi 30", short="Lo 30",
       yf="gross_prof_assets", side="high",
       note="operating-profitability sort as the published proxy"),
    _f("GS",      "Sales growth",                     "growth",
       yf="rev_growth", side="high"),
    _f("INDMOM",  "Industry momentum",                "momentum"),
    _f("ISKEW",   "Idiosyncratic skewness",           "risk", yf="iskew", side="low"),
    _f("ISSUE12", "Share issuance (12m)",             "issuance", live="sort",
       ds="Portfolios_Formed_on_NI", long="Lo 20", short="Hi 20"),
    _f("ISSUE36", "Share issuance (36m)",             "issuance"),
    _f("IVG",     "Inventory growth",                 "investment"),
    _f("IVOL",    "Idiosyncratic volatility",         "risk", live="sort",
       ds="Portfolios_Formed_on_RESVAR", long="Lo 20", short="Hi 20",
       yf="ivol", side="low"),
    _f("LNOACHG", "Growth in long-term NOA",          "investment"),
    _f("LTR",     "Long-term reversal",               "momentum", live="factor",
       ds="F-F_LT_Reversal_Factor", col="LT_Rev"),
    _f("LVG",     "Leverage",                         "risk",
       yf="debt_to_equity", side="high"),
    _f("LVGBM",   "Leverage component of B/M",        "valuation"),
    _f("MAXRET",  "Extreme stock returns",            "risk", yf="maxret", side="low"),
    _f("MOM",     "Momentum (12-2)",                  "momentum", live="factor",
       ds="F-F_Momentum_Factor", col="Mom", yf="mom_12_2", side="high"),
    _f("NCOACHG", "Noncurrent operating assets chg",  "investment"),
    _f("NOA",     "Net operating assets",             "investment"),
    _f("NWCCHG",  "Net working capital changes",      "investment"),
    _f("OL",      "Operating leverage",               "quality"),
    _f("OSCORE",  "Ohlson O-score",                   "quality"),
    _f("PM",      "Profit margin",                    "quality",
       yf="profit_margin", side="high"),
    _f("PMCHG",   "Change in profit margin",          "quality"),
    _f("PPACHG",  "ΔPP&E / assets",                   "investment"),
    _f("QMJ",     "Quality minus junk",               "quality", live="aqr", aqr="QMJ"),
    _f("RER",     "Real estate holdings",             "other"),
    _f("REVSURP", "Revenue surprises",                "momentum"),
    _f("ROA",     "Return on assets",                 "quality", yf="roa", side="high"),
    _f("ROE",     "Return on equity",                 "quality", yf="roe", side="high"),
    _f("SEASONAL", "Return seasonality",              "momentum"),
    _f("SHORTINT", "Short interest",                  "trading"),
    _f("SMB",     "Market equity (size)",             "risk", live="sort",
       ds="Portfolios_Formed_on_ME", long="Lo 30", short="Hi 30",
       yf="mktcap", side="low"),
    _f("SP",      "Sales-to-price",                   "valuation", yf="sp", side="high"),
    _f("STR",     "Short-term reversal",              "momentum", live="factor",
       ds="F-F_ST_Reversal_Factor", col="ST_Rev", yf="str_1m", side="low"),
    _f("SUSGR",   "Sustainable growth",               "growth"),
    _f("TURNOVER", "Share volume",                    "trading",
       yf="turnover", side="low"),
    _f("VOLMTRN", "Volume trend",                     "trading"),
    _f("WH52",    "52-week high",                     "momentum", yf="wh52", side="high"),
    _f("XFIN",    "External financing",               "issuance"),
    _f("XRDAT",   "R&D / assets",                     "other"),
    _f("XRDMV",   "R&D / market value",               "other"),
    _f("XRDS",    "R&D / sales",                      "other"),
    _f("ZSCORE",  "Altman Z-score",                   "quality"),
]

# supplemental live factor (not one of the paper's 65, shown alongside):
AQR_SUPPLEMENTAL: list[dict] = [
    _f("HMLDEV", "HML Devil (Asness-Frazzini value)", "valuation",
       live="aqr", aqr="HMLDEV"),
]

# --- plain-English definition + "how to screen for it" recipe per AQR factor -
# Long side first in every recipe; sorted portfolios in the paper use a
# 30/40/30 split within large and small halves.
AQR_DEFS: dict[str, tuple[str, str]] = {
    "ABNINV":  ("Abnormal capital investment: capex far above the firm's own recent norm predicts poor returns.",
                "Compute capex ÷ average capex of the prior 3 years; LONG the lowest ~30%, short the binge spenders."),
    "ACC":     ("Accruals: earnings not backed by cash flow (accounting profits > cash profits) reverse later.",
                "Accruals = (net income − operating cash flow) ÷ total assets; LONG the lowest ~30%, short the highest."),
    "AD2MV":   ("Advertising intensity: heavy advertisers per dollar of market cap earn higher returns.",
                "Advertising expense ÷ market cap; LONG the highest ~30%."),
    "ADVERTCHG": ("Change in advertising: rising ad budgets signal management confidence.",
                "Year-over-year % change in advertising expense; LONG the biggest increases."),
    "AIM":     ("Amihud illiquidity: stocks whose price moves a lot per dollar traded earn a liquidity premium.",
                "Average |daily return| ÷ daily dollar volume over ~3 months; LONG the most illiquid ~30%."),
    "ASSETG":  ("Asset growth: balance-sheet empire builders underperform; asset shrinkers outperform.",
                "Year-over-year % change in total assets; LONG the lowest ~30%, short the fastest growers."),
    "ATO":     ("Asset turnover: revenue squeezed from each dollar of assets — an efficiency measure.",
                "Sales ÷ total assets; LONG the highest ~30%."),
    "ATOCHG":  ("Improving efficiency: rising asset turnover predicts higher returns.",
                "Year-over-year change in (sales ÷ assets); LONG the biggest improvements."),
    "BAB":     ("Betting against beta: low-beta stocks earn higher RISK-ADJUSTED returns than high-beta.",
                "12-month beta vs the market; LONG low-beta (levered up), short high-beta (delevered)."),
    "BM":      ("Book-to-market: the classic value factor — cheap price relative to accounting book value.",
                "Book equity ÷ market cap; LONG the highest ~30% (value), short the lowest (growth/glamour)."),
    "CAPTO":   ("Capital turnover: sales generated per dollar of invested capital.",
                "Sales ÷ (equity + debt); LONG the highest ~30%."),
    "CASH":    ("Cash holdings: cash-rich firms (relative to assets) earn higher subsequent returns.",
                "Cash & equivalents ÷ total assets; LONG the highest ~30%."),
    "CEGTH":   ("Capex growth: rapid capital-expenditure growth precedes disappointment.",
                "Year-over-year % growth in capex; LONG the LOWEST ~30%."),
    "CP":      ("Cash flow-to-price: value measured with cash flow instead of accounting earnings.",
                "Operating cash flow ÷ market cap; LONG the highest ~30%."),
    "DCAP":    ("Debt capacity: tangible-asset-heavy firms can borrow more; the mix predicts returns.",
                "Tangible assets (PP&E, inventory, receivables) ÷ total assets vs leverage; LONG high spare capacity."),
    "DELAY":   ("Price delay: stocks slow to absorb market-wide news earn a neglected-stock premium.",
                "Share of return variance explained by LAGGED market returns; LONG the most delayed ~30%."),
    "DP":      ("Dividend yield: high payout per dollar of price, a defensive value tilt.",
                "Trailing 12-month dividends ÷ price; LONG the highest ~30%."),
    "ECONS":   ("Earnings consistency: firms with steady multi-year earnings growth streaks outperform.",
                "Count consecutive years of earnings growth; LONG the most consistent growers."),
    "ENTBM":   ("Enterprise book-to-market: value using the whole enterprise (debt + equity), not just equity.",
                "(Book equity + debt − cash) ÷ (market cap + debt − cash); LONG the highest ~30%."),
    "ENTMULT": ("Enterprise multiple: EV/EBITDA — the acquirer's valuation lens; low multiple = cheap.",
                "Enterprise value ÷ EBITDA; LONG the LOWEST ~30%, short the most expensive."),
    "EP":      ("Earnings-to-price: the earnings-yield version of value.",
                "Trailing earnings ÷ market cap (inverse P/E); LONG the highest ~30%."),
    "EPSMOM":  ("EPS momentum: sustained earnings-per-share growth persists into future returns.",
                "Rank on trailing multi-quarter EPS growth trend; LONG the strongest."),
    "FREECF":  ("Free cash flow-to-book: cash generation relative to book equity.",
                "Free cash flow ÷ book equity; LONG the highest ~30%."),
    "FSCORE":  ("Piotroski F-score: nine accounting health checks (profitability, leverage, efficiency).",
                "Score 0-9 (ROA>0, CF>0, improving margins/turnover, falling leverage…); LONG scores 8-9."),
    "GRPROF":  ("Gross profitability: revenue minus cost of goods, scaled by assets — 'quality's cleanest measure'.",
                "(Revenue − COGS) ÷ total assets; LONG the highest ~30%."),
    "GS":      ("Sales growth (contrarian): past high-growth glamour stocks DISAPPOINT.",
                "Trailing 5-year sales growth rank; LONG the LOWEST, short the glamour growers."),
    "INDMOM":  ("Industry momentum: whole industries trend — last winners' industries keep winning.",
                "Rank industries on trailing 6-12 month return; LONG stocks in top industries, short bottom."),
    "ISKEW":   ("Idiosyncratic skewness: lottery-like stocks (occasional huge up days) are overpriced.",
                "Skewness of daily residual returns over 1 year; LONG the LOWEST skew ~30%."),
    "ISSUE12": ("Share issuance (1y): companies printing new shares underperform; net buybacks outperform.",
                "12-month % change in split-adjusted shares outstanding; LONG the lowest/negative ~30%."),
    "ISSUE36": ("Share issuance (3y): the same dilution effect measured over three years.",
                "36-month % growth in shares outstanding; LONG the lowest ~30%."),
    "IVG":     ("Inventory growth: bulging inventories precede margin trouble.",
                "Year-over-year % change in inventory; LONG the LOWEST ~30%."),
    "IVOL":    ("Idiosyncratic volatility: the most volatile-for-no-reason stocks earn LOW returns.",
                "Std-dev of daily residuals vs the market over 1 year; LONG the LOWEST ~30%."),
    "LNOACHG": ("Growth in long-term net operating assets: aggressive operating-asset expansion reverses.",
                "Change in (long-term operating assets − liabilities) ÷ assets; LONG the lowest."),
    "LTR":     ("Long-term reversal: 3-5 year losers become winners (overreaction unwinds).",
                "Return from month −60 to −13; LONG the LOSERS, short the long-run winners."),
    "LVG":     ("Leverage: more debt per dollar of book equity carries a return premium.",
                "Total debt ÷ book equity; LONG the highest ~30%."),
    "LVGBM":   ("Leverage component of book-to-market: the part of value driven by debt structure.",
                "Decompose B/M into leverage vs enterprise components; LONG high leverage-driven value."),
    "MAXRET":  ("Lottery demand: stocks with a huge single up-day last month get overbought.",
                "Max daily return in the prior month; LONG the LOWEST ~30%, short the lottery tickets."),
    "MOM":     ("Momentum (12-2): the flagship — last year's winners (excluding last month) keep winning.",
                "Return from month −12 to −2; LONG the top ~30%, short the losers."),
    "NCOACHG": ("Noncurrent operating assets change: growth in long-term operating assets predicts weakness.",
                "Change in noncurrent operating assets ÷ total assets; LONG the lowest."),
    "NOA":     ("Net operating assets: balance sheets bloated with past accounting profits underperform.",
                "(Operating assets − operating liabilities) ÷ lagged assets; LONG the LOWEST ~30%."),
    "NWCCHG":  ("Net working capital changes: rising working capital consumes cash quietly.",
                "Change in (current assets − current liabilities) ÷ assets; LONG the lowest."),
    "OL":      ("Operating leverage: high fixed-cost businesses carry macro risk that is compensated.",
                "Operating costs (COGS + SG&A) ÷ total assets; LONG the highest ~30%."),
    "OSCORE":  ("Ohlson O-score: bankruptcy probability from size, leverage, profitability, liquidity.",
                "Compute the O-score logit; LONG the SAFEST ~30%, short likely-distress names."),
    "PM":      ("Profit margin: net income kept from each dollar of sales.",
                "Net income ÷ sales; LONG the highest ~30%."),
    "PMCHG":   ("Margin improvement: expanding profit margins precede outperformance.",
                "Year-over-year change in profit margin; LONG the biggest improvements."),
    "PPACHG":  ("PP&E growth: heavy additions to plant and equipment (scaled by assets) reverse.",
                "Change in gross PP&E ÷ total assets; LONG the lowest."),
    "QMJ":     ("Quality minus junk: profitable, growing, safe, high-payout stocks vs their opposites.",
                "Composite z-score of profitability + growth + safety + payout; LONG top quality, short junk."),
    "RER":     ("Real estate ratio: firms heavy in real estate carry compensated macro risk.",
                "Buildings + capitalized leases ÷ PP&E; LONG the highest within each industry."),
    "REVSURP": ("Revenue surprises: beating revenue expectations drifts upward afterward.",
                "Latest revenue vs consensus (or vs same quarter last year, scaled); LONG the biggest beats."),
    "ROA":     ("Return on assets: straightforward profitability on the whole balance sheet.",
                "Net income ÷ total assets; LONG the highest ~30%."),
    "ROE":     ("Return on equity: profitability per dollar of shareholder capital.",
                "Net income ÷ book equity; LONG the highest ~30%."),
    "SEASONAL": ("Return seasonality: stocks that historically do well in THIS calendar month repeat.",
                "Average this-month return over the past 20 years; LONG the strongest seasonal names."),
    "SHORTINT": ("Short interest: heavily shorted stocks underperform — the shorts are usually right.",
                "Shares short ÷ shares outstanding; LONG the LEAST shorted ~30%."),
    "SMB":     ("Size: small caps earn more than mega caps over time.",
                "Market cap; LONG the smallest ~30%, short the largest."),
    "SP":      ("Sales-to-price: value via revenue — sturdy against accounting noise.",
                "Trailing sales ÷ market cap; LONG the highest ~30%."),
    "STR":     ("Short-term reversal: last month's biggest movers snap back.",
                "Prior 1-month return; LONG last month's LOSERS, short the winners."),
    "SUSGR":   ("Sustainable growth: book-equity growth a firm can fund internally predicts returns.",
                "Year-over-year growth in book equity; LONG the highest."),
    "TURNOVER": ("Share turnover: heavily traded (glamour) stocks underperform quiet ones.",
                "Monthly volume ÷ shares outstanding; LONG the LOWEST turnover ~30%."),
    "VOLMTRN": ("Volume trend: stocks with fading trading volume outperform those with surging volume.",
                "Slope of volume trend over ~6 months; LONG the declining-volume names."),
    "WH52":    ("52-week high: stocks near their 1-year high keep grinding up (anchoring).",
                "Price ÷ trailing 252-day high; LONG the closest to highs (ratio near 1)."),
    "XFIN":    ("External financing: firms raising outside money (equity + debt) underperform.",
                "(Equity issued − buybacks + net new debt) ÷ assets; LONG the LOWEST ~30%."),
    "XRDAT":   ("R&D-to-assets: research intensity scaled by the balance sheet.",
                "R&D expense ÷ total assets; LONG the highest ~30%."),
    "XRDMV":   ("R&D-to-market: research intensity the market is not paying for.",
                "R&D expense ÷ market cap; LONG the highest ~30%."),
    "XRDS":    ("R&D-to-sales: research intensity relative to revenue.",
                "R&D expense ÷ sales; LONG the highest ~30%."),
    "ZSCORE":  ("Altman Z-score: classic bankruptcy-distance score; safer firms earn more.",
                "Z = 1.2·WC/TA + 1.4·RE/TA + 3.3·EBIT/TA + 0.6·MV/Debt + SALE/TA; LONG the highest."),
    "HMLDEV":  ("HML Devil: value (book-to-market) using CURRENT prices instead of stale year-end prices.",
                "Book equity ÷ up-to-date market cap; LONG the cheapest ~30% — more responsive than classic HML."),
}

# --- OSAP acronym -> Russell-1000 characteristic (recreated-signal screens) --
# Only signals whose characteristic the free-data engine actually computes.
# Values must be keys produced by families/replication (see CHAR_META).
OSAP_CHAR_MAP: dict[str, str] = {
    "BM": "book_to_market", "BMdec": "book_to_market",
    "Beta": "beta", "BetaFP": "beta",
    "Cash": "cash_to_mv",
    "CF": "cfp", "cfp": "cfp",
    "DivYieldST": "div_yield",
    "EP": "ep",
    "EntMult": "ev_ebitda",
    "GP": "gross_prof_assets",
    "High52": "wh52",
    "IdioVol3F": "ivol", "IdioVolAHT": "ivol",
    "Illiquidity": "amihud",
    "MaxRet": "maxret",
    "Mom12m": "mom_12_2", "Mom6m": "mom_6m",
    "Price": "price",
    "RealizedVol": "realized_vol",
    "ReturnSkew": "iskew", "ReturnSkew3F": "iskew",
    "RoE": "roe", "roaq": "roa",
    "SP": "sp",
    "STreversal": "str_1m",
    "ShareVol": "turnover", "VolMkt": "turnover",
    "Size": "mktcap",
    "AssetGrowth": "asset_growth",
    "BookLeverage": "debt_to_equity",
}

# --- characteristic metadata (screens + stock-finder labels) -----------------
# high_is: what a HIGH raw value means for the classic premium — "long" (buy
# high values) or "short" (buy low values).
CHAR_META: dict[str, dict] = {
    "mktcap":          {"label": "Market cap", "high_is": "short",
                        "desc": "Size premium is long the SMALLEST names."},
    "book_to_market":  {"label": "Book-to-market", "high_is": "long",
                        "desc": "1 ÷ price-to-book. High = cheap (value)."},
    "ep":              {"label": "Earnings yield (E/P)", "high_is": "long",
                        "desc": "1 ÷ trailing P/E. High = cheap on earnings."},
    "sp":              {"label": "Sales yield (S/P)", "high_is": "long",
                        "desc": "1 ÷ price-to-sales. High = cheap on revenue."},
    "cfp":             {"label": "Cash flow / price", "high_is": "long",
                        "desc": "Operating cash flow ÷ market cap."},
    "div_yield":       {"label": "Dividend yield", "high_is": "long",
                        "desc": "Trailing dividends ÷ price."},
    "roe":             {"label": "Return on equity", "high_is": "long",
                        "desc": "Net income ÷ book equity."},
    "roa":             {"label": "Return on assets", "high_is": "long",
                        "desc": "Net income ÷ total assets."},
    "profit_margin":   {"label": "Profit margin", "high_is": "long",
                        "desc": "Net income ÷ sales."},
    "rev_growth":      {"label": "Revenue growth", "high_is": "long",
                        "desc": "Year-over-year sales growth (as tracked by growth funds)."},
    "debt_to_equity":  {"label": "Debt / equity", "high_is": "long",
                        "desc": "Bhandari leverage premium is long HIGH leverage. Handle with care."},
    "ev_ebitda":       {"label": "EV / EBITDA", "high_is": "short",
                        "desc": "Enterprise multiple. LOW = cheap (the long side)."},
    "cash_to_mv":      {"label": "Cash / market cap", "high_is": "long",
                        "desc": "Cash & equivalents ÷ market cap (cash-holdings premium)."},
    "fcf_to_mv":       {"label": "Free cash flow yield", "high_is": "long",
                        "desc": "Free cash flow ÷ market cap."},
    "mom_12_2":        {"label": "Momentum 12-2", "high_is": "long",
                        "desc": "Return from 12 months ago to 1 month ago."},
    "mom_6m":          {"label": "Momentum 6-1", "high_is": "long",
                        "desc": "Return from 6 months ago to 1 month ago."},
    "str_1m":          {"label": "Prior 1-month return", "high_is": "short",
                        "desc": "Short-term REVERSAL: long last month's losers."},
    "wh52":            {"label": "Closeness to 52w high", "high_is": "long",
                        "desc": "Price ÷ 252-day high (1.0 = at the high)."},
    "maxret":          {"label": "Max daily return (1m)", "high_is": "short",
                        "desc": "Lottery effect: long the LOWEST max-day names."},
    "ivol":            {"label": "Idiosyncratic vol", "high_is": "short",
                        "desc": "Residual daily vol vs SPY, annualized. Long the calmest."},
    "realized_vol":    {"label": "Realized vol (1y)", "high_is": "short",
                        "desc": "Total daily vol, annualized. Long the calmest."},
    "beta":            {"label": "Beta vs SPY", "high_is": "short",
                        "desc": "Betting-against-beta is long LOW beta."},
    "iskew":           {"label": "Return skewness", "high_is": "short",
                        "desc": "Lottery skew: long the LEAST positively skewed."},
    "turnover":        {"label": "Turnover", "high_is": "short",
                        "desc": "Dollar volume ÷ market cap. Long the quietly traded."},
    "amihud":          {"label": "Amihud illiquidity", "high_is": "long",
                        "desc": "|return| per dollar traded. Long the most illiquid."},
    "price":           {"label": "Share price", "high_is": "short",
                        "desc": "Nominal price effect: long LOW-priced stocks."},
    "asset_growth":    {"label": "Asset growth", "high_is": "short",
                        "desc": "YoY total-asset growth. Long the SHRINKERS."},
    "gross_prof_assets": {"label": "Gross profit / assets", "high_is": "long",
                        "desc": "(Revenue − COGS) ÷ total assets (Novy-Marx quality)."},
}
