"""Curated factor / strategic-beta ETFs (parsed once from the Morningstar US ETF
Universe BETA spreadsheets, top-by-AUM per factor, + a few explicit names). ticker
-> (factor_label, name). Folded into the Factor-Rotation universe as group='beta'.
Generated; safe to hand-edit."""

from __future__ import annotations

BETA_ETFS: dict[str, tuple[str, str]] = {
    'ACWV': ('LowVol', 'iShares MSCI Global Min Vol Factor ETF'),
    'AGGY': ('FixedIncome', 'WisdomTree Yield Enhanced US Aggt Bd E'),
    'AQLT': ('Quality', 'iShares MSCI Global Quality Factor ETF'),
    'BWZ': ('FixedIncome', 'State Street® SPDR® BlmbgSTIntrnTrsBdE'),
    'BYLD': ('FixedIncome', 'iShares Yield Optimized Bond ETF'),
    'CALF': ('Fundamental', 'Pacer US Small Cap Cash Cows 100 ETF'),
    'CERY': ('Commodity', 'State StreetSPDRBbgEnhRlYldCmdStrNoK1E'),
    'CFA': ('LowVol', 'VictoryShares US 500 Volatility Wtd ET'),
    'CFO': ('LowVol', 'VictoryShares US 500 Enh Vol Wtd ETF'),
    'CMDY': ('Commodity', 'iShares Blmbrg Roll Sel Cmdty Strart E'),
    'COM': ('Commodity', 'Direxion Auspice Broad Cmdty Strat ETF'),
    'COWG': ('Fundamental', 'Pacer US Large Cp CA Cows Gr Ldrs ETF'),
    'COWZ': ('Other', 'Pacer US Cash Cows 100 ETF'),
    'CSD': ('Spinoff', 'Invesco S&P Spin-Off'),
    'CSM': ('Multifactor', 'ProShares Large Cap Core Plus'),
    'DBA': ('Commodity', 'Invesco DB Agriculture'),
    'DBB': ('Commodity', 'Invesco DB Base Metals'),
    'DBC': ('Commodity', 'Invesco DB Commodity Tracking'),
    'DBO': ('Commodity', 'Invesco DB Oil'),
    'DBP': ('Commodity', 'Invesco DB Precious Metals'),
    'DGRO': ('Dividend', 'iShares Core Dividend Growth ETF'),
    'DGRW': ('Dividend', 'WisdomTree US Quality Dividend Gr ETF'),
    'DIAL': ('FixedIncome', 'Columbia Diversified Fixed Inc Allc ET'),
    'DLN': ('Dividend', 'WisdomTree US LargeCap Dividend ETF'),
    'DVY': ('Dividend', 'iShares Select Dividend ETF'),
    'DWAS': ('Momentum', 'Invesco Dorsey Wright SmallCap Momt ET'),
    'DXJ': ('Dividend', 'WisdomTree Japan Hedged Equity ETF'),
    'EELV': ('LowVol', 'Invesco S&P Emerging Markets Low Vol E'),
    'EEMV': ('LowVol', 'iShares MSCI Emerg Mkts Min Vol Fctr E'),
    'EFAV': ('LowVol', 'iShares MSCI EAFE Min Vol Factor ETF'),
    'EFG': ('Growth', 'iShares MSCI EAFE Growth ETF'),
    'EFV': ('Value', 'iShares MSCI EAFE Value ETF'),
    'EMGF': ('Multifactor', 'iShares Em Mkts Eq Fac ETF'),
    'EPI': ('Fundamental', 'WisdomTree India Earnings ETF'),
    'EPS': ('Fundamental', 'WisdomTree U.S. LargeCap Fund'),
    'EQAL': ('Other', 'Invesco Russell 1000 Equal Weight ETF'),
    'EQWL': ('Other', 'Invesco S&P 100 Equal Weight ETF'),
    'EUSA': ('Other', 'iShares MSCI USA Equal Weighted ETF'),
    'EZM': ('Fundamental', 'WisdomTree U.S. MidCap Earnings ETF'),
    'FDL': ('Dividend', 'First Trust Morningstar Div Leaders ET'),
    'FDLO': ('LowVol', 'Fidelity Low Volatility Factor ETF'),
    'FDMO': ('Momentum', 'Fidelity Momentum Factor ETF'),
    'FDVV': ('Dividend', 'Fidelity High Dividend ETF'),
    'FEX': ('Multifactor', 'First Trust Large Cap Core AlphaDEX® E'),
    'FLDR': ('FixedIncome', 'Fidelity Low Duration Bond Factor ETF'),
    'FLQL': ('Multifactor', 'Franklin US Large Cap Mltfctr Idx ETF'),
    'FLQM': ('Multifactor', 'Franklin US Mid Cap Mltfctr Idx ETF'),
    'FNDA': ('Fundamental', 'Schwab Fundamental U.S. Small CompanyE'),
    'FNDB': ('Fundamental', 'Schwab Fundamental U.S. Broad Market E'),
    'FNDC': ('Fundamental', 'Schwab Fundamental International SmEqE'),
    'FNDE': ('Fundamental', 'Schwab Fundamental Emerging MarketsEqE'),
    'FNDF': ('Fundamental', 'Schwab Fundamental International Eq ET'),
    'FNDX': ('Fundamental', 'Schwab Fundamental U.S. Large CompanyE'),
    'FNX': ('Multifactor', 'First Trust Mid Cap Core AlphaDEX® ETF'),
    'FQAL': ('Quality', 'Fidelity Quality Factor ETF'),
    'FSMD': ('Multifactor', 'Fidelity Small-Mid Multifactor ETF'),
    'FTC': ('Multifactor', 'First Trust Large Cap Gr AlphaDEX® ETF'),
    'FTCS': ('Quality', 'First Trust Capital Strength ETF'),
    'FTXL': ('Multifactor', 'First Trust Nasdaq Semiconductor ETF'),
    'FV': ('Momentum', 'First Trust Dorsey Wright Focus 5 ETF'),
    'FVD': ('Dividend', 'First Trust Value Line® Dividend ETF'),
    'FXL': ('Multifactor', 'First Trust Technology AlphaDEX® ETF'),
    'GCOR': ('FixedIncome', 'Goldman Sachs Access US Aggregate Bd E'),
    'GEM': ('Multifactor', 'Goldman Sachs ActiveBeta® EMkts Eq ETF'),
    'GIGB': ('FixedIncome', 'Goldman Sachs Acss Invmt Grd Corp Bd E'),
    'GSEW': ('Other', 'Goldman Sachs Equal Wght US Lg Cp Eq E'),
    'GSIE': ('Multifactor', 'Goldman Sachs ActiveBeta® Intl Eq ETF'),
    'GSLC': ('Multifactor', 'Goldman Sachs ActiveBeta® US LgCp Eq E'),
    'GSWO': ('Multifactor', 'Goldman Sachs ActiveBeta World Eq ETF'),
    'GTIP': ('FixedIncome', 'Goldman Sachs Acs Infl Protd USD Bd ET'),
    'GURU': ('HedgeFund', 'Global X Guru'),
    'HDV': ('Dividend', 'iShares Core High Dividend ETF'),
    'HGER': ('Commodity', 'Harbor Commodity All-Weather StrategyE'),
    'HYGV': ('FixedIncome', 'FlexShares HY Val-Scrd Bd'),
    'ICOW': ('Other', 'Pacer Dev Mkts Intl Csh Cows 100 ETF'),
    'IDHQ': ('Quality', 'Invesco S&P International Dev Qual ETF'),
    'IDLV': ('LowVol', 'Invesco S&P Intl Dev Low Vol ETF'),
    'IDMO': ('Momentum', 'Invesco S&P International Dev Momt ETF'),
    'IDV': ('Dividend', 'iShares International Select Div ETF'),
    'IFLN': ('FixedIncome', 'Invesco Bloomberg Enh Flln Angls ETF'),
    'IFV': ('Momentum', 'First Trust Dorsey Wright Intl Foc 5'),
    'IJH': ('Core', 'iShares Core S&P MidCap'),
    'IJJ': ('Value', 'iShares S&P Mid-Cap 400 Value ETF'),
    'IJK': ('Growth', 'iShares S&P Mid-Cap 400 Growth ETF'),
    'IJS': ('Value', 'iShares S&P Small-Cap 600 Value ETF'),
    'IJT': ('Growth', 'iShares S&P Small-Cap 600 Growth ETF'),
    'ILCG': ('Growth', 'iShares Morningstar Growth ETF'),
    'IMCG': ('Growth', 'iShares Morningstar Mid-Cap Growth ETF'),
    'IMTM': ('Momentum', 'iShares MSCI Intl Momentum Factor ETF'),
    'INTF': ('Multifactor', 'iShares International Equity Factor ET'),
    'IPKW': ('Other', 'Invesco Intl BuyBack Achiev™ ETF'),
    'IPO': ('IPO', 'Renaissance IPO'),
    'IQLT': ('Quality', 'iShares MSCI Intl Quality Factor ETF'),
    'ISCF': ('Multifactor', 'iShares MSCI Intl Small-Cap Mltfct ETF'),
    'IUS': ('Fundamental', 'Invesco RAFI™ Strategic US ETF'),
    'IUSG': ('Growth', 'iShares Core S&P US Growth ETF'),
    'IUSV': ('Value', 'iShares Core S&P US Value ETF'),
    'IVE': ('Value', 'iShares S&P 500 Value ETF'),
    'IVLU': ('Value', 'iShares Edge MSCI Intl Value Factor ET'),
    'IVV': ('Core', 'iShares Core S&P 500'),
    'IVW': ('Growth', 'iShares S&P 500 Growth ETF'),
    'IWD': ('Value', 'iShares Russell 1000 Value ETF'),
    'IWF': ('Growth', 'iShares Russell 1000 Growth ETF'),
    'IWN': ('Value', 'iShares Russell 2000 Value ETF'),
    'IWO': ('Growth', 'iShares Russell 2000 Growth ETF'),
    'IWP': ('Growth', 'iShares Russell Mid-Cap Growth ETF'),
    'IWS': ('Value', 'iShares Russell Mid-Cap Value ETF'),
    'IWX': ('Value', 'iShares Russell Top 200 Value ETF'),
    'IWY': ('Growth', 'iShares Russell Top 200 Growth ETF'),
    'JHEM': ('Multifactor', 'JHancock Multifactor Em Mkts ETF'),
    'JHMD': ('Multifactor', 'JHancock Multifactor Developed Intl ET'),
    'JHML': ('Multifactor', 'JHancock Multifactor Large Cap ETF'),
    'JHMM': ('Multifactor', 'JHancock Multifactor Mid Cap ETF'),
    'JHSC': ('Multifactor', 'JHancock Multifactor Small Cap ETF'),
    'JMOM': ('Momentum', 'JPMorgan US Momentum Factor ETF'),
    'JOET': ('Quality', 'Virtus Terranova US Quality Momentum E'),
    'JPEM': ('Multifactor', 'JPMorgan Diversified Return EMkts Eq E'),
    'JPIN': ('Multifactor', 'JPMorgan Diversified Return Intl Eq ET'),
    'JPME': ('Multifactor', 'JPMorgan Divers Ret US Mid Cp Eq ETF'),
    'JPSE': ('Multifactor', 'JPMorgan Divers Ret US Small Cap Eq ET'),
    'JPUS': ('Multifactor', 'JPMorgan Diversified Return US Eq ETF'),
    'JQUA': ('Quality', 'JPMorgan US Quality Factor ETF'),
    'LQDH': ('LowVol', 'iShares Interest Rate Hedged Corp Bd E'),
    'LRGF': ('Multifactor', 'iShares U.S. Equity Factor ETF'),
    'MFDX': ('Multifactor', 'PIMCO RAFI Dyn Multi-Factor Intl Eq ET'),
    'MGK': ('Growth', 'Vanguard Mega Cap Growth ETF'),
    'MGV': ('Value', 'Vanguard Mega Cap Value ETF'),
    'MOAT': ('Quality', 'VanEck Morningstar Wide Moat ETF'),
    'MTUM': ('Momentum', 'iShares MSCI USA Momentum Factor ETF'),
    'MUST': ('FixedIncome', 'Columbia Multi-Sector Municipal Inc ET'),
    'NOBL': ('Dividend', 'ProShares S&P 500 Dividend Aristocrats'),
    'OILK': ('Commodity', 'ProShares K-1 Free Crude Oil ETF'),
    'OMFL': ('Multifactor', 'Invesco Russell 1000® Dynamic Mltfct E'),
    'ONEV': ('LowVol', 'Stt Strt® SPDR® Russell 1000 LwVolFocE'),
    'PCY': ('FixedIncome', 'Invesco Emerging Markets Sov Debt ETF'),
    'PDP': ('Momentum', 'Invesco Dorsey Wright Momentum ETF'),
    'PIE': ('Momentum', 'Invesco DW Emerging Markets Momt ETF'),
    'PIZ': ('Momentum', 'Invesco DW Developed Markets Momt ETF'),
    'PKW': ('Other', 'Invesco BuyBack Achievers ETF'),
    'PRF': ('Fundamental', 'Invesco RAFI US 1000 ETF'),
    'PRFZ': ('Fundamental', 'Invesco RAFI US 1500 Small-Mid ETF'),
    'PRN': ('Momentum', 'Invesco Dorsey Wright IndustrialsMomtE'),
    'PSI': ('Multifactor', 'Invesco Semiconductors ETF'),
    'PSK': ('Quality', 'Stt Strt® SPDR® ICE Preferred Secs ETF'),
    'PSP': ('PrivateEquity', 'Invesco Global Listed Private Eq'),
    'PTF': ('Momentum', 'Invesco Dorsey Wright Technology MomtE'),
    'PXF': ('Fundamental', 'Invesco RAFI Developed Markets ex-US E'),
    'PXH': ('Fundamental', 'Invesco RAFI Emerging Markets ETF'),
    'QEFA': ('Multifactor', 'State Street® SPDR® MSCI EAFE StrtFcsE'),
    'QGRW': ('Multifactor', 'WisdomTree U.S. Quality Growth ETF'),
    'QHY': ('FixedIncome', 'WisdomTree US Hi Yld Corp Bd'),
    'QQEW': ('Other', 'First Trust Nasdaq-100 Sel Eql Wght ET'),
    'QQQE': ('Other', 'Direxion NASDAQ-100® Equal Wtd ETF'),
    'QTEC': ('Other', 'First Trust NASDAQ-100-Tech Sector ETF'),
    'QUAL': ('Quality', 'iShares MSCI USA Quality Factor ETF'),
    'QUS': ('Multifactor', 'Stt Strt® SPDR® MSCI USA StratFacs ETF'),
    'QVML': ('Multifactor', 'Invesco S&P 500 QVM Multi-factor ETF'),
    'RDVY': ('Dividend', 'First Trust Rising Dividend Achiev ETF'),
    'RECS': ('Other', 'Columbia Research Enhanced Core ETF'),
    'RODM': ('Multifactor', 'Hartford Multifactor Dev Mkts (exUS) E'),
    'RSP': ('Other', 'Invesco S&P 500® Equal Weight ETF'),
    'RSPG': ('Other', 'Invesco S&P 500® Equal Weight Energy E'),
    'RSPH': ('Other', 'Invesco S&P 500® Equal Wt Hlth Care ET'),
    'RSPN': ('Other', 'Invesco S&P 500® Equal Wt Indls ETF'),
    'RSPT': ('Other', 'Invesco S&P 500® Equal Weight Tech ETF'),
    'RSPU': ('Other', 'Invesco S&P 500® Equal Weight Utilts E'),
    'RWJ': ('Fundamental', 'Invesco S&P SmallCap 600 Revenue ETF'),
    'RWK': ('Fundamental', 'Invesco S&P MidCap 400 Revenue ETF'),
    'RWL': ('Fundamental', 'Invesco S&P 500 Revenue ETF'),
    'SBND': ('FixedIncome', 'Columbia Short Duration Bond ETF'),
    'SCHD': ('Dividend', 'Schwab US Dividend Equity ETF™'),
    'SCHG': ('Growth', 'Schwab US Large-Cap Growth ETF™'),
    'SCHV': ('Value', 'Schwab US Large-Cap Value ETF™'),
    'SDCI': ('Commodity', 'USCF SummerHaven Dyn CmdtyStgy NoK-1 E'),
    'SDVY': ('Dividend', 'First Trust SMID Cp Rising Div Achv ET'),
    'SDY': ('Dividend', 'State Street® SPDR® S&P® Dividend ETF'),
    'SIZE': ('Size', 'iShares MSCI USA Size Factor'),
    'SLYG': ('Growth', 'State Street® SPDR® S&P 600™ Sm Cp GrE'),
    'SLYV': ('Value', 'State Street® SPDR® S&P 600™ Sm CpValE'),
    'SMLF': ('Multifactor', 'iShares U.S. Small-Cap Eq Fac ETF'),
    'SMMV': ('LowVol', 'iShares MSCI USA Sm-Cp Min Vol Fctr ET'),
    'SMOT': ('Quality', 'VanEck Morningstar SMID Moat ETF'),
    'SPGP': ('Multifactor', 'Invesco S&P 500 GARP ETF'),
    'SPHB': ('LowVol', 'Invesco S&P 500® High Beta ETF'),
    'SPHQ': ('Quality', 'Invesco S&P 500® Quality ETF'),
    'SPLV': ('LowVol', 'Invesco S&P 500® Low Volatility ETF'),
    'SPMO': ('Momentum', 'Invesco S&P 500® Momentum ETF'),
    'SPYD': ('Dividend', 'State Street SPDR Port S&P 500 HiDivET'),
    'SPYG': ('Growth', 'State Street SPDR Port S&P 500 Gr ETF'),
    'SPYV': ('Value', 'State Street SPDR Port S&P 500 Val ETF'),
    'TDTF': ('FixedIncome', 'FlexShares iBoxx 5Yr Target Dur TIPS E'),
    'TDTT': ('FixedIncome', 'FlexShares iBoxx 3Yr Target Dur TIPS E'),
    'TILT': ('Multifactor', 'FlexShares Mstar US Mkt Factors Tilt E'),
    'TLTW': ('Other', 'iShares 20+ Year Trs Bd Buywrt Stgy ET'),
    'TPIF': ('LowVol', 'Timothy Plan International ETF'),
    'TPLC': ('LowVol', 'Timothy Plan US Large/Mid Cap Core ETF'),
    'TPSC': ('LowVol', 'Timothy Plan US Small Cap Core ETF'),
    'USCI': ('Commodity', 'United States Commodity Index'),
    'USMV': ('LowVol', 'iShares MSCI USA Min Vol Factor ETF'),
    'USVM': ('Multifactor', 'VictoryShares US Sm Md Cp Val Momt ETF'),
    'VBK': ('Growth', 'Vanguard Small-Cap Growth ETF'),
    'VBR': ('Value', 'Vanguard Small-Cap Value ETF'),
    'VFLO': ('Fundamental', 'VictoryShares Free Cash Flow ETF'),
    'VIDI': ('Multifactor', 'Vident International Equity Strategy E'),
    'VIG': ('Dividend', 'Vanguard Dividend Appreciation ETF'),
    'VIGI': ('Dividend', 'Vanguard Intl Div Apprec ETF'),
    'VLUE': ('Value', 'iShares MSCI USA Value Factor ETF'),
    'VOE': ('Value', 'Vanguard Mid-Cap Value ETF'),
    'VONG': ('Growth', 'Vanguard Russell 1000 Growth ETF'),
    'VONV': ('Value', 'Vanguard Russell 1000 Value ETF'),
    'VOOG': ('Growth', 'Vanguard S&P 500 Growth ETF'),
    'VOOV': ('Value', 'Vanguard S&P 500 Value ETF'),
    'VOT': ('Growth', 'Vanguard Mid-Cap Growth ETF'),
    'VTV': ('Value', 'Vanguard Value ETF'),
    'VUG': ('Growth', 'Vanguard Growth ETF'),
    'VUSE': ('Quality', 'Vident U.S. Equity Strategy ETF'),
    'VYM': ('Dividend', 'Vanguard High Dividend Yield ETF'),
    'VYMI': ('Dividend', 'Vanguard Intl Hi Div Yld Idx ETF'),
    'WEAT': ('Commodity', 'Teucrium Wheat Fund'),
    'XCCC': ('LowVol', 'BondBloxx CCC Rated USD HY Corp Bd ETF'),
    'XMHQ': ('Quality', 'Invesco S&P MidCap Quality ETF'),
    'XMLV': ('LowVol', 'Invesco S&P MidCap Low Volatility ETF'),
    'XMMO': ('Momentum', 'Invesco S&P MidCap Momentum ETF'),
    'XNTK': ('Other', 'State Street® SPDR® NYSE Technology ET'),
    'XSHQ': ('Quality', 'Invesco S&P SmallCap Quality ETF'),
    'XSLV': ('LowVol', 'Invesco S&P SmallCap Low Volatility ET'),
    'XSMO': ('Momentum', 'Invesco S&P SmallCap Momentum ETF'),
}


def beta_tickers() -> list[str]:
    return list(BETA_ETFS)


def beta_tag(ticker: str):
    """(factor_label, name) or None."""
    return BETA_ETFS.get(ticker)
